disabled_rules:
- array_init
- block_based_kvo
- conditional_returns_on_newline
- closure_end_indentation
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_xctest_method
- explicit_acl 
- explicit_top_level_acl 
- explicit_type_interface
- file_header
- file_types_order
- function_default_parameter_at_end
- implicit_return
- implicitly_unwrapped_optional
- inclusive_language
- missing_docs
- multiline_arguments_brackets
- multiline_parameters_brackets	
- no_extension_access_modifier
- no_grouping_extension
- nslocalizedstring_require_bundle
- object_literal
- pattern_matching_keywords
- prohibited_interface_builder
- redundant_type_annotation
- required_deinit
- single_test_class
- sorted_imports
- strict_fileprivate
- strong_iboutlet
- switch_case_on_newline 
- trailing_closure
- trailing_whitespace
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_whitespace_between_cases
- yoda_condition

# Temporary disabled
- lower_acl_than_parent

opt_in_rules:
- anyobject_protocol
- attributes
- class_delegate_protocol
- closing_brace
- closure_body_length
- closure_spacing
- collection_alignment
- colon
- comma
- compiler_protocol_init
- contains_over_first_not_nil
- control_statement
- convenience_type
- cyclomatic_complexity
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- explicit_init
- extension_access_modifier
- fallthrough 
- fatal_error_message
- first_where
- for_where
- generic_type_name
- identical_operands
- implicit_getter
- inert_defer
- is_disjoint
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor	
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- literal_expression_end_indentation
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- nimble_operator
- no_fallthrough_only
- notification_center_detachment
- nslocalizedstring_key
- nsobject_prefer_isequal
- number_separator
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- override_in_extension
- prefixed_toplevel_constant
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order	
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- reduce_boolean
- reduce_into  
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- sorted_first_last
- statement_position
- static_operator
- switch_case_alignment
- syntactic_sugar
- todo
- toggle_bool
- trailing_comma
- trailing_newline
- trailing_semicolon
- type_contents_order
- unneeded_break_in_switch
- unowned_variable_capture
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try: warning # explicitly
line_length: 160
function_parameter_count:
    warning: 10
    error: 15
closure_body_length:
    warning: 50
    error: 100
function_body_length:
    warning: 100
    error: 150
type_body_length:
    warning: 300
    error: 400
file_length:
    warning: 600
    error: 1200
nesting:
  type_level:
    warning: 5
    error: 5
  function_level:
    warning: 1
    error: 1
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 2 # only warning
    max_length: # warning and error
        warning: 100
        error: 100
    excluded: "TestAbstractionTests"
identifier_name:
    min_length: # only min_length
        error: 2 # only error
    excluded: # excluded via string array
        - id

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Templates
